```{r}
library(ggplot2)
library(caTools)
library(readr)
library(downloader)
library(caTools)
library(FNN)
library(readxl)

data <- readRDS("/Users/michelle/Downloads/DSRP/DSRP-2024-Shaunette/MichelleProject/merged_data.rds")
na_count <- sum(is.na(data$complaint_count))
na_count # 9829 

df_new <- data %>% select(-complaint_count)
df_new <- na.omit(df_new)
View(df_new)
dim(df_new)
(get_dupes(df_new, c(longitude, latitude)))
na_count <- sum(is.na(data$quarter))
na_count # 9829 

View(data)
dim(data)
print(sum(data$inspection_count))
```

```{r}
set.seed(42)

data <- data[, c('percent_aged_16_unemployed', 'hardship_index', 'complaint_count', 'avg_risk', 'inspection_count')]
split <- sample.split(data$pass_count, SplitRatio = 0.8)
train_data <- subset(data, split == TRUE)
test_data <- subset(data, split == FALSE)
```

```{r}
# Fit the KNN model using the training data
knn_model <- knn(train = train_data[, c('percent_aged_16_unemployed', 'hardship_index', 'complaint_count', 'avg_risk')],
                 test = test_data[, c('percent_aged_16_unemployed', 'hardship_index', 'complaint_count', 'avg_risk')],
                 cl = train_data$inspection_count,
                 k=5)
```

```{r}
knn_model_2 <- knn(train = train_data[, c('percent_aged_16_unemployed', 'hardship_index', 'complaint_count', 'avg_risk', 'inspection_count')],
                 test = test_data[, c('percent_aged_16_unemployed', 'hardship_index', 'complaint_count', 'avg_risk', 'inspection_count')],
                 cl = train_data$pass_count,
                 k=5)


```

```{r}
# Test model
pred <- knn_model
pred_2 <- knn_model_2
```

```{r}
#first confusion matrix
confusion_matrix <- table(test_data$inspection_count, pred)
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)

print(confusion_matrix)
print(accuracy )
```

```{r}
# second confusion matrix
confusion_matrix <- table(test_data$pass_count, pred_2)
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)

print(confusion_matrix)
print(accuracy )
```
